### ISSUE TITLE
Working with ARRI logC3 and C4 footage using AGX.

### ISSUE THREAD

**Issue by wesley0chang** [sobotka/AgX-Resolve#5]
Hi Troy, I'm Wesley, a freelance colorist, thank you for creating the AGX DCTL for us, it gave me great results in projects I've been working on.
While doing some tests the past few days, I've had problems working with native ARRI footage, with LogC4 footage, I transform it into LogC3 and use the DCTL. With LogC3 footage, I just simply use the DCTL. They gave me identical results, but both of their exposure seems to be slightly off. ( Didn't have this issue working with footage from other camera manufacturers or Blender render.)

Is there something I'm doing wrong or any suggestion I can fix the problem I've encountered,
Thank you, sir.

**Comment by sobotka** [comment]
Hello Wes. Great to hear you are finding some utility in this.

The AgX mechanic works in any colourspace. As such, all you will need to do is integrate the LogCv4 and whatever gamut you prefer to work in.

LogCv4 moves the “middle grey”, so you will need to change the output middle grey value.

**Comment by sobotka** [comment]
> Hello Wes. Great to hear you are finding some utility in this.
> 
> The AgX mechanic works in any colourspace. As such, all you will need to do is integrate the LogCv4 and whatever gamut you prefer to work in.
> 
> LogCv4 moves the “middle grey”, so you will need to change the output middle grey value. It is significantly lower than v3.

**Comment by wesley0chang** [comment]
Thank you Troy, I've done a few tests, and all worked fine.
Thanks again for the DCTL and Agx in Blender it made the colors much more realistic and pleasing. 
Beast Regards!
