### ISSUE TITLE
AgX-Resolve: Blender to DaVinci workflow

### ISSUE THREAD

**Issue by Johannes164** [sobotka/AgX-Resolve#7]
# Sorry if this is too unrelated/spam
I've recently started using Blender, and **I know very little, if anything, about colour** theory, post-processing, colour grading, or anything similar. 
My question is whether it will be possible to use the _AgX-Resolve_ files in combination with EXR files from Blender, as explained in [this](https://youtu.be/-UjJqwwMJc8?si=zqW0Q2PJmaxYfeJd) video made by [Polyfjord](https://www.youtube.com/@Polyfjord)

I tried following the tutorial, using the _Filmic resolve_ "Scene Linear to Base Encoding", and then using the _AgX_ on the second node instead of the _Filmic_ one, which did not work. I then tried only using the _Kraken-AgX.dctl_, which looked a lot better. However, I wouldn't know if it did its thing properly. 
Additionally, whenever I used the _AgX-Resolve_ LUT, DaVinci gave the image a Resolve Studio watermark, indicating there is some difference <sub>(maybe file format, I don't know)</sub> between the _AgX-Resolve_ file and the _Filmic resolve_ files that makes _AgX-Resolve_ unavailable on the free version of DaVinci Resolve.

## Summary:
1. Will it be possible to use AgX-Resolve in the way explained by Polyfjord? If so, when?
2. Will it be available on the free version of DaVinci Resolve?

**Comment by sobotka** [comment]
> Will it be possible to use AgX-Resolve in the way explained by Polyfjord? If so, when? 

You did not link to any information sadly, so I can’t say one way or the other.

Good news, though…

Gleb Alexandrov is in the process of finalizing a large tutorial on how to do some grading etc. in Resolve, and has a pretty deep dive into the transforms.

I recently uploaded an AgX-Kraken DCTL that, assuming one has the Studio version, should be able to achieve 1:1 stimuli for pictures formed using the AgX-Kraken repository. If you do not have the Studio version of Resolve, the AgX DCTL won’t be of much use, but Gleb’s tutorial will help with using the OCIO configuration in Resolve’s Fusion. 

I am not interested in supporting what Eary’s AgX did to end up in Blender, so there will not be a DCTL to support that specific picture formation.

I’m reasonably confident that the formed pictures will be more or less similar for grading purposes though.

> Will it be available on the free version of DaVinci Resolve?

No, DCTLs will not work with the free version of Resolve, only the paid Studio version. One can still use the Resolve Fusion interface to create an OpenColorIO transform chain in the free edition of Resolve, however.

That clear things up?

**Comment by Johannes164** [comment]
Sorry about the links, the Polyfjord video I referred to is a Youtube video titled "Tutorial: Real-time EXR Workflow | DaVinci Resolve + Blender" and the link is https://www.youtube.com/watch?v=-UjJqwwMJc8

Either way, thanks for the response, ill look out for that tutorial :)

**Comment by sobotka** [comment]
I reckon you can probably solve this in ten minutes of experimenting before Gleb’s tutorial lands.

1. Locate the OpenColorIO configuration of your choice.
1. Open Resolve.
1. Load an EXR onto the timeline and flip to the Fusion tab.
1. In the nodes, add the appropriate OpenColorIO transform chain.
1. Adjust to your liking in the Color tab.

Post how you did it somewhere.
